# version: "3"

# services:
#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     environment:
#       RABBITMQ_DEFAULT_USER: user
#       RABBITMQ_DEFAULT_PASS: password

#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: user
#       MONGO_INITDB_ROOT_PASSWORD: password
#       MONGO_INITDB_DATABASE: takehometest
#     volumes:
#       - mongodb_data:/data/db

#   app:
#     build:
#       context: ./
#       dockerfile: DockerFile
#     container_name: nestjs-app
#     ports:
#       - 3001:3001
#     depends_on:
#       - mongodb
#       - rabbitmq
#     environment:
#       DATABASE_URI: mongodb://mongodb:27017
#       DATABASE_NAME: takehometest
#       DATABASE_USER: user
#       DATABASE_PASS: password
#     networks:
#       - backend

# networks:
#   backend:
#     driver: bridge

# volumes:
#   mongodb_data:


version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nestjs:
    build:
      context: .
      dockerfile: DockerFile
    container_name: nestjs
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongodb:27017/yourdbname
      - RABBITMQ_URL=amqp://rabbitmq:5672
    command: npm run start:prod
    
networks:
  default:
    name: app_network

volumes:
  mongodb_data:
